# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookShow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Cosmos', '~> 16.0'
  # Pods for BookShow
  

end
